version: 1.0.{build}-{branch}-{configuration}-{platform}

branches:
  only:
    - master

image:
  - LLVM 18.1.6 x64
  - LLVM (Clang) 17.0.0
  - CMake 3.28.1


build_script:
  - cd {clone_folder}
  - ./sumo cfg
  - ./sumo build
