version: 1.{build}-{branch}

branches:
  only:
    - master

image:
  - Visual Studio 2022
  - Ubuntu2204
  - macos-monterey


for:
  -
    matrix:
       only:
        - image: Visual Studio 2022
    build_script:
      - cd C:\projects\sumolang
      - sumo cfg
      - sumo build
  -
    matrix:
       only:
        - image: macos-monterey
    build_script:
      - cd /Users/appveyor/projects/sumolang
      - sh ./sumo.sh cfg
      - sh ./sumo.sh build
  -
    matrix:
        only:
          - image: Ubuntu2204
    build_script:
      - cd /home/appveyor/projects/sumolang
      - sh ./sumo.sh cfg
      - sh ./sumo.sh build