version: 1.0.{build}-{branch}-{configuration}-{platform}

branches:
  only:
    - master

- for:
   - matrix:
      only:
       - LLVM (Clang) 17.0.0
       - CMake 3.28.1
  clone_folder: /dev/sumo

image:
  - LLVM 18.1.6 x64
  - LLVM (Clang) 17.0.0
  - CMake 3.28.1

- for:
   - matrix:
      only:
       - LLVM (Clang) 17.0.0
       - CMake 3.28.1
  clone_folder: /dev/sumo

- for:
  - matrix:
      only:
        - LLVM 18.1.6 x64
  clone_folder: C:\sumo

build_script:
  - cd {clone_folder}
  - ./sumo cfg
  - ./sumo build


